name: Auto-version on tag

on:
  push:
    tags:
      - '*'

jobs:
  set_version:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Version
        id: package_version
        uses: KageKirin/set-csproj-version@v0
        with:
          file: ./ModShardLauncher.Templates.csproj
          version: ${{ github.ref_name  }}

      - name: Commit New Version
        run: |
          git commit -am "CI: updated version from tag"
          git push https://${{ github.token  }}@github.com/remyCases/ModShardLauncherTemplate
