name: Auto-version on tag

on:
  push:
    tags:
      - '*'

jobs:
  set_version:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Version
        id: package_version
        uses: KageKirin/set-csproj-version@v0
        with:
          file: ./ModShardLauncher.Templates.csproj
          version: ${{ github.ref_name  }}

      - name: Set user info
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit & Push changes
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
